name: Publish

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    name: Publish GeoQibla
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Set release version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION_NAME=${VERSION}" >> "$GITHUB_ENV"

      - name: Publish to Maven Central
        run: ./gradlew :shared:publishToMavenCentral -PVERSION_NAME="$VERSION_NAME" --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
